[package]
name = "curb"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "The Calimero Curb Contract"
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk.workspace = true
